### ISSUE TITLE
获取布局时出现错误

### ISSUE THREAD

**Issue by zhongke-wang** [ysbing/YADB#25]
此报错在获取布局时概率性出现，系统版本安卓9

```
MainException:java.util.concurrent.TimeoutException
        at com.ysbing.yadb.layout.LayoutShell.get(LayoutShell.java:26)
        at com.ysbing.yadb.layout.Layout.run(Layout.java:19)
        at com.ysbing.yadb.Main.main(Main.java:40)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:383)
```

**Comment by ysbing** [comment]
你打开Logcat，看下执行命令那瞬间出现了什么异常，贴上来

**Comment by zhongke-wang** [comment]
```
2024-05-31 16:48:58.355 10988-10988 app_process             app_process                          W  Failed to determine odex file name: Dex location /data/local/tmp/yadb has no extension.
2024-05-31 16:48:58.410 10988-10988 main                    app_process                          W  type=1400 audit(0.0:51300): avc: denied { read } for name="u:object_r:vendor_mpctl_prop:s0" dev="tmpfs" ino=4423 scontext=u:r:shell:s0 tcontext=u:object_r:vendor_mpctl_prop:s0 tclass=file permissive=0
2024-05-31 16:48:58.424 10988-10988 libc                    app_process                          E  Access denied finding property "ro.vendor.at_library"
2024-05-31 16:48:58.442 10988-10988 AndroidRuntime          app_process                          D  Calling main entry com.ysbing.yadb.Main
2024-05-31 16:49:03.547 10988-10988 AndroidRuntime          app_process                          D  Shutting down VM
```
